### ISSUE TITLE
expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Lize-59** [yourh/DeepGraphGO#10]
您好！最近在拜读您《DeepGraphGO: graph neural network for large-scale,multispecies protein function prediction》一文时，对文章使用的方法颇有兴趣，在尝试运行DeepGraphGO时（已配置需要的环境），发现程序有参数传入为空的问题，本人编程能力较弱，希望得到解答，谢谢！
![image](https://user-images.githubusercontent.com/85621015/145341267-b4d68da0-b23c-4734-99cf-c5406b5ee897.png)

**Comment by yourh** [comment]
你修改了代码吗？直接按照readme里experiments运行scripts里的sh就行了。具体如何运行main.py参考scripts下的脚本即可。

**Comment by Lize-59** [comment]
感谢解答，我尝试一下。



------------------ Original ------------------
From: YRH ***@***.***&gt;
Date: 周五,12月 10,2021 18:20
To: yourh/DeepGraphGO ***@***.***&gt;
Cc: Lize-59 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [yourh/DeepGraphGO] expected str, bytes or os.PathLike object, not NoneType (Issue #10)





 
你修改了代码吗？直接按照readme里experiments运行scripts里的sh就行了。具体如何运行main.py参考scripts下的脚本即可。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
