### ISSUE TITLE
对前期的数据处理代码深感兴趣

### ISSUE THREAD

**Issue by Lize-59** [yourh/DeepGraphGO#11]
非常感谢上次的解答，在多次拜读您的文章之后，再对照代码进行理解，得到了很大的帮助。您在处理蛋白质相互关系时采用的思路更是为我对数据处理方面有了新的见解。对您的蛋白质相关数据处理方面的源代码（如何对数据库原始数据进行处理）十分感兴趣，在此恳请您能否方便给予一份处理原始数据的源代码，深表感激，若有不便之处，也无关紧要，谢谢！

**Comment by yourh** [comment]
不好意思，这部分代码没有整理，暂时没有公开的计划。
