### ISSUE TITLE
data.zip partial failure

### ISSUE THREAD

**Issue by KangshengQi** [yourh/DeepGraphGO#21]
Hello,

When I attempted to unzip the data.zip file, I was only able to extract a few of the data files instead of all the required ones. Would it be possible for you to share the complete dataset used for training and testing with me?

Thank you!

**Comment by yourh** [comment]
How would you prefer me to share the dataset?

**Comment by KangshengQi** [comment]
I was able to extract the files. I needed to be on a linux machine using dtrx in order to do so.
