### ISSUE TITLE
Annotate user's input sequences?

### ISSUE THREAD

**Issue by yangliume** [yourh/DeepGraphGO#3]
Dear DeepGraphGO developers,

Thank you for your great work! Congratulations! DeepGraphGO has outperformed DeepGOplus in many ways, especially the high number of true annotations and the extremely low number of false annotations. 

I would like to have a trial on my personal protein datasets. If I understand correctly, I have not found a way to use DeepGraphGO for user's input sequences, right? If there is anyways to do that, please let me know, thank you very much!

Yang

**Comment by yourh** [comment]
You can predict or retrain the model on this version of PPI network (with another training dataset) by modifying the configure files. If you want to use another version of PPI network, you need to run InterProScan on the proteins of your PPI network, convert them to binary features, and create a dgl format PPI network (after normalization).

**Comment by yangliume** [comment]
> You can predict or retrain the model on this version of PPI network (with another training dataset) by modifying the configure files. If you want to use another version of PPI network, you need to run InterProScan on the proteins of your PPI network, convert them to binary features, and create a dgl format PPI network (after normalization).

Thank you for your quick reply! I manage to annotate my personal protein datasets, it works like a charm, thank you!
