### ISSUE TITLE
关于ppi_mat.npz和ppi_pid_list.txt之间的关联关系

### ISSUE THREAD

**Issue by liutong19991016** [yourh/DeepGraphGO#4]
您好，通过您的源代码我发现DeepGraphGO整个蛋白质网络是通过ppi_mat.npz构建出来的，但是ppi_pid_list.txt文件里面只列举出了实验中所有的蛋白质名称，除此之外暂未发现其他可以表明蛋白质相互作用的文件，因此无法将ppi_pid_list.txt中的蛋白质名称与ppi_mat.npz中的数据联系起来。我大胆猜测ppi_mat.npz中的每一行代表一种蛋白质，并且顺序与ppi_pid_list.txt中的蛋白质名称相对应，不知道是不是这样的呢？
非常抱歉打扰到您，希望您能稍微解答一下我的疑问，感谢！

**Comment by yourh** [comment]
是你理解的这样的，ppi_mat.npz和ppi_pid_list.txt的顺序是一致的

**Comment by liutong19991016** [comment]
非常感谢您的回复！
