### ISSUE TITLE
关于bp任务下训练集、测试集、验证集中的蛋白质不在总的ppi_pid_list.txt中

### ISSUE THREAD

**Issue by liutong19991016** [yourh/DeepGraphGO#5]
作者您好，很抱歉再次打扰到您，我在统计bp任务下数据使用情况的时候发现，bp任务下训练集、测试集、验证集中的蛋白质不在总的ppi_pid_list.txt中，比如bp_train_pid_list.txt中的第一个蛋白质Q5BHC4就不存在ppi_pid_list.txt中，不知道这是什么情况呢？还是我对您们提出的DeepGraphGO理解的还不到位。作为新入门图神经网络的菜鸟，我的理解是训练集、测试集、验证集中的蛋白质应该都需要出现在ppi_pid_list.txt中，因为整个ppi网络就是通过ppi_pid_list.txt这个邻接矩阵来构建的，如果训练集中突然出现了新的节点，不知道网络会怎么处理这些新的节点呢？非常抱歉打扰到您，希望您能解答一下我的疑惑，感谢！

**Comment by yourh** [comment]
PPI网络本来就只涵盖有限的蛋白质，所以训练集、验证集和测试集中都会有没有网络信息的蛋白质。训练的时候会忽略没有网络信息的蛋白质，预测的时候没有网络信息的蛋白质通过有网络信息的同源蛋白质。具体这些你仔细阅读一下论文和代码就知道了。

**Comment by liutong19991016** [comment]
太感谢啦，非常抱歉再次打扰到您！
