### ISSUE TITLE
关于PPI的问题

### ISSUE THREAD

**Issue by Alexzhuan** [yourh/DeepGraphGO#6]
作者您好，有个关于PPI网络的问题想请教下。我看到你们论文中提到用STRING11.0，其中有上千万蛋白质，但是为什么你们ppi_mat中只有十多万个蛋白质？

**Comment by yourh** [comment]
我们使用的网络里只包括了CAFA3的目标物种相关的蛋白质。

**Comment by Alexzhuan** [comment]
噢噢，好的，感谢！

**Comment by Alexzhuan** [comment]
您好，还有一个问题想请教下，你们是如何对edge weights做normalization的，是像GeneMANIA那样，w_ij / sqrt(D_i * D_j), D_i为i节点所有weight求和

**Comment by yourh** [comment]
嗯，是用的类似的normalization。
