### ISSUE TITLE
关于文章中提到的“多物种策略”

### ISSUE THREAD

**Issue by liutong19991016** [yourh/DeepGraphGO#7]
作者您好，抱歉再次打扰到您。文章中提到的多物种策略相比于先前的工作取得了很大的进步，这是毋庸置疑的。对此，我有一个疑问：您论文中在对DeepGraphGO模型进行直观展示的时候我注意到，每个物种都分别属于一个子图，那么是不是每个物种的子图之间都有边相连呢？如果没有边相连，是根据什么其他途径来进行消息传播的呢？也就是，如果多个物种之间彼此没有边相连的话，多个物种之间是如何通过GCN进行消息传播，进而相互影响，最终根据已有蛋白质的功能信息去推测出未知的蛋白质功能信息的呢？

**Comment by yourh** [comment]
不同物种的蛋白质之间没有边相连，但是不同物种的蛋白质共享特征空间和整个模型的参数，所以能够相互影响。具体可以再仔细阅读论文。
