### ISSUE TITLE
关于数据问题

### ISSUE THREAD

**Issue by SerendipityCreate** [yourh/DeepGraphGO#9]
你好，这个数据ppi_dgl_top_100似乎没有给出来，是否方便提供

**Comment by yourh** [comment]
README中的运行步骤里，第一句 `./scripts/preprocessing.sh` 就是用来生成ppi_dgl_top_100的。请问是生成的时候有问题吗？

**Comment by SerendipityCreate** [comment]
好的，没有问题了，谢谢
